### ISSUE TITLE
Add the ability to conveniently obtain ApplicationContext from LifecycleHooks

### ISSUE THREAD

**Issue by martyn0ff** [jqwik-team/jqwik-spring#8]
Hey,

Currently I'm obtaining `ApplicationContext` in my custom LifecycleHooks like so:

```java
...
Class<?> testClass = context.containerClass();
Object testInstance = context.testInstance();
Field[] declaredFields = testClass.getDeclaredFields();
ApplicationContext applicationContext = Arrays.stream(declaredFields)
        .filter(f -> ApplicationContext.class.isAssignableFrom(f.getType()))
        .findFirst()
        .map(f -> tryGetFieldValue(testInstance, f, ApplicationContext.class))
        .orElseThrow(() -> new RuntimeException("ApplicationContext instance is not found in container class."));
...
```

It does the job, but requires a container to have `ApplicationContext` injected as a field. Not the end of the world, but can be improved.
I couldn't find a way to get a hold of `TestContextManager` from within a custom hook, however I've noticed that `JqwikSpringExtension` uses it: https://github.com/jqwik-team/jqwik-spring/blob/f95cb14f2be66f401bf19204ba598f938e0a5e6a/src/main/java/net/jqwik/spring/JqwikSpringExtension.java#L17

Spring itself offers a static method  `getApplicationContext` in `SpringExtension` to retrieve a context in one line, which is quite simple: https://github.com/spring-projects/spring-framework/blob/699f93fed71f7bfd73d94188dce6b849c92927cc/spring-test/src/main/java/org/springframework/test/context/junit/jupiter/SpringExtension.java#L354

It would be nice to have an ability to obtain an instance of Spring context in similar fashion, maybe directly from `JqwikSpringExtension`, given that jqwik's hooks closely mimic that of JUnit's.

**Comment by jlink** [comment]
Thanks for the suggestion @martyn0ff.
I'll have a look at how Spring testing support does it. If it's easy to do, it should come soon.

**Comment by jlink** [comment]
@martyn0ff 

Would a convenience method like that help you?

```java
public class JqwikSpringExtension {

    public Optional<ApplicationContext> applicationContext(LifecycleContext context) {
        return ....;
    }
}
```

**Comment by martyn0ff** [comment]
@jlink Yes, that works well.

**Comment by jlink** [comment]
I added a new class `JqwikSpringLifecycleSupport` for this method.
See https://github.com/jqwik-team/jqwik-spring#support-for-jqwik-lifecycle-hooks

Available in version `0.12.0-SNAPSHOT`.

@martyn0ff I can release it if it works for you.

**Comment by martyn0ff** [comment]
@jlink Great to hear! I will test it soon. Is this in Maven repositories? If so, which repo? I've never used snapshot libraries before.

**Comment by jlink** [comment]
@martyn0ff See https://jqwik.net/docs/current/user-guide.html#snapshot-releases

**Comment by martyn0ff** [comment]
@jlink Gave it a whirl. Works well with `PropertyLifecycleContext`, however does not work with `ContainerLifecycleContext` - which I also faced before, I have to use before/after property hooks to get a hold of Spring context.

**Comment by jlink** [comment]
> Works well with `PropertyLifecycleContext`, however does not work with `ContainerLifecycleContext`

My bad. Let me fix this.

**Comment by jlink** [comment]
Give it a try now. Make sure that the snapshot dependency will be updated.

**Comment by martyn0ff** [comment]
I've fetched `jqwik-spring-0.12.0-20240107.135138`, but that still does not work. In its source I see that it only attempts to retrieve the context for instances of `MethodLifecycleContext`. These implemented only by try and property hooks.

**Comment by martyn0ff** [comment]
OK, fetched the correct one. Can confirm that it work!
